from pygame import Color, Vector2

SCREEN_WIDTH = 1500
SCREEN_HEIGHT = 900

BALL_RADIUS = 15
BALL_STARTING_POS = Vector2(SCREEN_WIDTH/2, SCREEN_HEIGHT / 2)
BALL_STARTING_X_SPEED = 10
BALL_STARTING_Y_SPEED = 20

PLAYER_WIDTH = 30
PLAYER_HEIGHT = 200
PLAYER_SIZE = Vector2(PLAYER_WIDTH, PLAYER_HEIGHT)
PLAYER_SPEED = 20

PLAYER1_ID = 1
PLAYER1_STARTING_POS = Vector2(
    SCREEN_WIDTH / 15,
    (SCREEN_HEIGHT / 2)-(PLAYER_HEIGHT/2))

PLAYER2_ID = 2
PLAYER2_STARTING_POS = Vector2(
    SCREEN_WIDTH - (SCREEN_WIDTH / 15) - PLAYER_WIDTH,
    (SCREEN_HEIGHT / 2)-(PLAYER_HEIGHT/2))

TERRAIN_LINE_WIDTH = 9
TERRAIN_LINE_COUNT = 10
TERRAIN_SPACE_BETWEEM_LINES = 20
TERRAIN_COLOUR = Color(155, 155, 155)

WALL_THICKNESS = 15
WALL_COLOUR = Color(100, 100, 100)
TOP_BOTTOM_WALL_SIZE = Vector2(SCREEN_WIDTH, WALL_THICKNESS)

LEFT_RIGHT_GOAL_SIZE = Vector2(WALL_THICKNESS, SCREEN_HEIGHT)

# Player Controller Constraints
PLAYER_MIN_Y_POS = WALL_THICKNESS
PLAYER_MAX_Y_POS = int(SCREEN_HEIGHT - PLAYER_SIZE.y - WALL_THICKNESS)

SCORE_SIZE = 200
SCORE_COLOUR = Color(255, 255, 255)

PAUSE_TIME = 1.5
